// examples/adapters/qwik/src/main.tsx
/** @jsxImportSource @builder.io/qwik */
import '@gridla/demo-kit/tokens.css'
import '@gridla/demo-kit/demo.css'
import './style.css'

import { component$, render, useSignal, useStore } from '@builder.io/qwik'

import type { GridLayout } from 'gridla'
import {
  GridCanvas,
  GridItem,
  GridPreviewOutline,
  GridProvider,
  useGridItemView,
  useGridRuntime,
} from 'gridla/qwik'
import { dashboardLayout, formatRect } from '@gridla/demo-kit'

// The Qwik demo app. It renders the shared dashboard layout with `gridla/qwik`
// (client-side rendered here; the same components render on the server in a
// Qwik City app) and drives the shared adapter contract tests
// (tests/e2e/specs/adapters.qwik.e2e.ts). The Qwik optimizer runs through
// qwik-loader.cjs; see rsbuild.config.ts.

type Data = { label: string }

const DemoItem = component$<{ id: string; label: string; body: string }>(({ id, label, body }) => {
  const view = useGridItemView(id)
  return (
    <GridItem id={id} class="gd-item" resizeEdges={['e', 's', 'se']} resizeHandleClass="gd-handle">
      <div class="gd-item-head">
        <span>{label}</span>
        <span class="gd-item-coords">{formatRect(view.value.rect)}</span>
      </div>
      <div class="gd-item-body">{body}</div>
    </GridItem>
  )
})

const Toolbar = component$<{ counter: { value: number } }>(({ counter }) => {
  const runtime = useGridRuntime<Data>()
  return (
    <button
      type="button"
      class="gd-button"
      data-variant="primary"
      onClick$={() => {
        const n = counter.value + 1
        counter.value = n
        runtime.controller?.actions.place(
          { id: `new-${n}`, w: 220, h: 140, minW: 80, minH: 60, data: { label: `New ${n}` } },
          { pointer: { x: 480, y: 300 } },
        )
      }}
    >
      Add item
    </button>
  )
})

const App = component$(() => {
  const layout = useSignal<GridLayout<Data>>(dashboardLayout())
  const gap = useSignal(12)
  const counter = useSignal(0)
  const status = useStore({ strategy: 'none', reason: '', commits: 0 })

  return (
    <main class="page">
      <header class="page-head">
        <div>
          <h1>Gridla with Qwik</h1>
          <p>
            <code>GridProvider</code> renders the layout on the server from props and creates the
            controller in a visible task on the client. <code>GridCanvas</code> measures itself and
            binds pointer and keyboard input, and <code>GridItem</code> positions each child. The
            layout state is yours: this page keeps it in a signal.
          </p>
        </div>
      </header>
      <GridProvider
        layout={layout.value}
        gap={gap.value}
        snapDistance={24}
        onLayoutChange$={(next) => {
          layout.value = next as GridLayout<Data>
        }}
        onCommit$={(detail) => {
          status.strategy = detail.strategy ?? 'none'
          status.reason = detail.reason
          status.commits += 1
        }}
      >
        <section class="gd-stage stage">
          <GridCanvas>
            {layout.value.items.map((item) => (
              <DemoItem
                key={item.id}
                id={item.id}
                label={item.data?.label ?? item.id}
                body={
                  item.id === 'header'
                    ? 'fixed height · flexes horizontally'
                    : 'drag me · resize from the edges'
                }
              />
            ))}
            <GridPreviewOutline class="gd-preview" />
          </GridCanvas>
        </section>
        <div class="toolbar">
          <Toolbar counter={counter} />
          <button
            type="button"
            class="gd-button"
            onClick$={() => {
              layout.value = dashboardLayout()
            }}
          >
            Reset
          </button>
          <label>
            Gap {gap.value}
            <input
              class="gd-range"
              type="range"
              min={0}
              max={32}
              step={2}
              value={gap.value}
              onInput$={(_, element) => {
                gap.value = Number(element.value)
              }}
            />
          </label>
        </div>
      </GridProvider>
      <p class="page-note" data-testid="status">
        {layout.value.items.length} items · last strategy: {status.strategy}
        {status.reason ? ` (${status.reason})` : ''} · commits: {status.commits}
      </p>
    </main>
  )
})

void render(document.getElementById('root') as HTMLElement, <App />)

// examples/adapters/preact/src/main.tsx
import '@gridla/demo-kit/tokens.css'
import '@gridla/demo-kit/demo.css'
import './style.css'

import { useState } from 'react'
import { createRoot } from 'react-dom/client'

import type { GridLayout } from 'gridla'
import { GridCanvas, GridProvider, useGridActions, type GridChangeDetail } from 'gridla/react'
import { dashboardLayout } from '@gridla/demo-kit'
import {
  Button,
  ControlGroup,
  DemoFrame,
  DemoItem,
  DemoPreview,
  Inspector,
  RangeField,
  ThemeSwitch,
  Toggle,
} from '@gridla/demo-kit/react'

// The Preact demo app. It is the React example rendered by Preact: `react`
// and `react-dom` are aliased to `preact/compat` in rsbuild.config.ts, and the
// code below imports from `gridla/react` unchanged. It drives the shared
// adapter contract tests (tests/e2e/specs/adapters.preact.e2e.ts).

type Data = { label: string }

function Toolbar({
  scrollable,
  setScrollable,
}: {
  scrollable: boolean
  setScrollable: (v: boolean) => void
}) {
  const actions = useGridActions<Data>()
  const [counter, setCounter] = useState(0)
  return (
    <ControlGroup title="Actions">
      <div className="gd-actions">
        <Button
          variant="primary"
          onClick={() => {
            const n = counter + 1
            setCounter(n)
            actions.place(
              { id: `new-${n}`, w: 220, h: 140, minW: 80, minH: 60, data: { label: `New ${n}` } },
              { pointer: { x: 480, y: 300 } },
            )
          }}
        >
          Add item
        </Button>
        <Button onClick={() => actions.setLayout(dashboardLayout())}>Reset</Button>
      </div>
      <Toggle label="Scrollable canvas" checked={scrollable} onChange={setScrollable} />
    </ControlGroup>
  )
}

function App() {
  const [layout, setLayout] = useState<GridLayout<Data>>(() => dashboardLayout())
  const [gap, setGap] = useState(12)
  const [snapDistance, setSnapDistance] = useState(24)
  const [scrollable, setScrollable] = useState(false)
  const [lastCommit, setLastCommit] = useState<GridChangeDetail | null>(null)
  const effective: GridLayout<Data> = scrollable
    ? { ...layout, canvas: { ...layout.canvas, heightMode: 'scrollable' } }
    : { ...layout, canvas: { ...layout.canvas, heightMode: 'bounded' } }

  return (
    <main className="page">
      <header className="page-head">
        <div>
          <h1>Gridla with Preact</h1>
          <p>
            The React adapter running on <code>preact/compat</code>. <code>GridProvider</code> owns
            the layout, <code>GridCanvas</code> measures itself and handles pointer and keyboard
            input, and <code>GridItem</code> positions each child. Nothing in this page imports
            React itself.
          </p>
        </div>
        <ThemeSwitch />
      </header>
      <GridProvider<Data>
        layout={effective}
        onLayoutChange={setLayout}
        onCommit={setLastCommit}
        gap={gap}
        snapDistance={snapDistance}
      >
        <DemoFrame
          stageLabel="controlled · projected to the stage"
          stageStyle={{ height: 480 }}
          scrollable={scrollable}
          stage={
            <GridCanvas style={{ minHeight: '100%' }}>
              {layout.items.map((item) => (
                <DemoItem key={item.id} id={item.id} label={item.data?.label}>
                  {item.id === 'header'
                    ? 'fixed height · flexes horizontally'
                    : 'drag me · resize from the edges'}
                </DemoItem>
              ))}
              <DemoPreview />
            </GridCanvas>
          }
          controls={
            <>
              <ControlGroup title="Solver">
                <RangeField label="Gap" value={gap} min={0} max={32} step={2} onChange={setGap} />
                <RangeField
                  label="Snap distance"
                  value={snapDistance}
                  min={0}
                  max={64}
                  step={4}
                  onChange={setSnapDistance}
                />
              </ControlGroup>
              <Toolbar scrollable={scrollable} setScrollable={setScrollable} />
            </>
          }
          inspector={<Inspector />}
        />
      </GridProvider>
      <p className="page-note" data-testid="status">
        {layout.items.length} items · last strategy:{' '}
        {lastCommit ? `${lastCommit.strategy ?? 'none'} (${lastCommit.reason})` : 'none'}
      </p>
    </main>
  )
}

createRoot(document.getElementById('root') as HTMLElement).render(<App />)
