// packages/gridla/src/qwik/components.tsx
/** @jsxImportSource @builder.io/qwik */
import {
  component$,
  Slot,
  useSignal,
  useVisibleTask$,
  type CSSProperties,
  type PropFunction,
  type PropsOf,
} from '@builder.io/qwik'

import type { GridResizeEdge } from '../core'
import { GRID_DATA } from '../interaction/attributes'
import { createPointerGesture } from '../interaction/gesture'
import { observeSize } from '../interaction/measure'
import { useGridContext } from './context'
import { rectStyle, resizeHandleStyle, selectItemView, type GridPositioning } from './view'

type DivProps = Omit<PropsOf<'div'>, 'style' | 'children' | 'ref'> & {
  /** Inline styles merged over the geometry styles. Object form only. */
  style?: CSSProperties
}

// ---------------------------------------------------------------------------
// GridCanvas
// ---------------------------------------------------------------------------

/**
 * Props for `GridCanvas`: `div` attributes (except `style`, which must be an
 * object) plus the pointer gesture options.
 */
export type GridCanvasProps = DivProps & {
  /** Fires when a press on an item ends without a drag. */
  onItemClick$?: PropFunction<(itemId: string) => void>
  /** Fires when Delete or Backspace is pressed while an item is selected. */
  onDeleteKey$?: PropFunction<(itemId: string) => void>
  /** Set to `false` to ignore pointer input. Default `true`. */
  enabled?: boolean
}

/**
 * The element items are positioned in. Measures itself, feeds the size to the
 * provider, and binds pointer and keyboard handling with native listeners.
 * Renders a `div` with `position: relative`; give it a height (or let it
 * follow the layout with `responsive={false}` on the provider).
 */
export const GridCanvas = component$<GridCanvasProps>(
  ({ onItemClick$, onDeleteKey$, enabled, style, ...rest }) => {
    const ctx = useGridContext()
    const ref = useSignal<HTMLDivElement>()

    // eslint-disable-next-line qwik/no-use-visible-task -- pointer binding needs the element
    useVisibleTask$(
      // oxlint-disable-next-line typescript/unbound-method -- task context methods are bound by Qwik
      ({ track, cleanup }) => {
        const controller = track(() => ctx.runtime.controller)
        const isEnabled = track(() => enabled)
        const element = ref.value
        if (!controller || !element) return
        controller.gesture.setElement(element)
        const pointer = createPointerGesture(controller, {
          scope: ctx.runtime.scope ?? null,
          enabled: isEnabled,
          onItemClick: onItemClick$ ? (itemId) => void onItemClick$(itemId) : undefined,
          onDeleteKey: onDeleteKey$ ? (itemId) => void onDeleteKey$(itemId) : undefined,
        })
        cleanup(pointer.bindPointer(element))
        cleanup(pointer.bindKeyboard(element))
        if (ctx.runtime.responsive) {
          cleanup(observeSize(element, (size) => controller.setSize(size)))
        }
        cleanup(() => {
          pointer.destroy()
          controller.gesture.setElement(null)
        })
      },
      { strategy: 'document-ready' },
    )

    const state = ctx.state.value
    const canvas = state.layout.canvas
    const dragging = state.interaction !== null
    const canvasStyle: CSSProperties = {
      position: 'relative',
      boxSizing: 'border-box',
      touchAction: 'none',
      userSelect: dragging ? 'none' : undefined,
      ...(ctx.runtime.responsive
        ? canvas.heightMode === 'scrollable'
          ? { minHeight: `${canvas.height}px` }
          : {}
        : { width: `${canvas.width}px`, height: `${canvas.height}px` }),
      ...style,
    }

    return (
      <div
        ref={ref}
        data-gridla-canvas=""
        data-gridla-active={dragging ? '' : undefined}
        tabIndex={rest.tabIndex ?? 0}
        {...rest}
        style={canvasStyle}
      >
        <Slot />
      </div>
    )
  },
)

// ---------------------------------------------------------------------------
// GridItem
// ---------------------------------------------------------------------------

/**
 * Props for `GridItem`. `id` selects the item; the rest control drag surfaces,
 * built-in resize handles, and how the element is positioned. Children are
 * projected through a `Slot`; read `useGridItemView(id)` for the item's
 * geometry and flags.
 */
export type GridItemProps = Omit<DivProps, 'id'> & {
  /** Id of the item in the layout. */
  id: string
  /**
   * `true` (default): the whole element is a drag surface. `false`: only
   * descendants marked with `data-gridla-drag-handle="<id>"` start a move.
   */
  draggable?: boolean
  /** Edges to render built-in resize handles for. Default: none. */
  resizeEdges?: readonly GridResizeEdge[]
  /** Class for built-in resize handles. */
  resizeHandleClass?: string
  /**
   * Position the element with `transform` (default) or with `left`/`top`.
   * Transform keeps layout work off the main thread during gestures.
   */
  positioning?: GridPositioning
  /** Render the cursor-tracked rect while dragging instead of the solved preview. Default `true`. */
  followPointer?: boolean
}

/**
 * Positions one item inside `GridCanvas`. Headless: it renders a `div` with
 * geometry styles and data attributes and leaves appearance to you.
 */
export const GridItem = component$<GridItemProps>(
  ({
    id,
    draggable = true,
    resizeEdges,
    resizeHandleClass,
    positioning = 'transform',
    followPointer = true,
    style,
    ...rest
  }) => {
    const ctx = useGridContext()
    const view = selectItemView(ctx.state.value, id)
    const shownRect =
      view.isActive && followPointer && view.activeRect && view.interaction?.mode === 'move'
        ? view.activeRect
        : view.rect
    const itemStyle: CSSProperties = {
      boxSizing: 'border-box',
      ...rectStyle(shownRect, positioning),
      ...(view.isActive ? { zIndex: 2 } : {}),
      ...(view.isTransferring ? { opacity: 0.4 } : {}),
      ...style,
    }

    return (
      <div
        {...rest}
        data-gridla-item={id}
        data-gridla-drag-handle={draggable ? id : undefined}
        data-gridla-active={view.isActive ? '' : undefined}
        data-gridla-selected={view.isSelected ? '' : undefined}
        data-gridla-shifted={view.isShifted ? '' : undefined}
        data-gridla-transferring={view.isTransferring ? '' : undefined}
        style={itemStyle}
      >
        <Slot />
        {resizeEdges?.map((edge) => (
          <div
            key={edge}
            class={resizeHandleClass}
            data-gridla-resize-handle={id}
            data-gridla-edge={edge}
            style={resizeHandleStyle(edge)}
          />
        ))}
      </div>
    )
  },
)

// ---------------------------------------------------------------------------
// GridPreviewOutline
// ---------------------------------------------------------------------------

/**
 * Props for `GridPreviewOutline`: `div` attributes plus the positioning mode
 * (`transform` by default).
 */
export type GridPreviewOutlineProps = DivProps & {
  positioning?: GridPositioning
}

/**
 * Renders a box where the active item will land when released. Renders
 * nothing when no gesture is in progress.
 */
export const GridPreviewOutline = component$<GridPreviewOutlineProps>(
  ({ positioning = 'transform', style, ...rest }) => {
    const ctx = useGridContext()
    const preview = ctx.state.value.preview
    if (!preview || !preview.accepted) return null
    // Read the fields directly: the optimizer drops an intermediate `const`
    // here and leaves an uninitialized declaration behind.
    const rect = { x: preview.item.x, y: preview.item.y, w: preview.item.w, h: preview.item.h }
    return (
      <div
        data-gridla-preview=""
        {...rest}
        style={{
          pointerEvents: 'none',
          boxSizing: 'border-box',
          ...rectStyle(rect, positioning),
          ...style,
        }}
      />
    )
  },
)

/** Attribute names the pointer gesture looks for. Re-exported from `gridla/interaction`. */
export { GRID_DATA }

// packages/gridla/src/react/components.tsx
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useLayoutEffect,
  useMemo,
  useRef,
  type CSSProperties,
  type HTMLAttributes,
  type ReactNode,
} from 'react'

import type { GridResizeEdge } from '../core'
import { useGridContext } from './context'
import { useGridItemView, useGridStore, type GridItemView } from './hooks'
import { rectStyle, resizeHandleStyle } from '../interaction/style'
import { GRID_DATA, useGridInteraction, type UseGridInteractionOptions } from './interaction'
import { useElementSize } from './measure'

// ---------------------------------------------------------------------------
// GridCanvas
// ---------------------------------------------------------------------------

/**
 * Props for `GridCanvas`: `div` attributes (except `onKeyDown`, which the canvas
 * owns) plus `UseGridInteractionOptions`.
 */
export type GridCanvasProps = Omit<HTMLAttributes<HTMLDivElement>, 'onKeyDown'> &
  UseGridInteractionOptions & {
    children?: ReactNode
  }

/**
 * The element items are positioned in. Measures itself, feeds the size to the
 * provider, and wires pointer and keyboard handling. Renders a `div` with
 * `position: relative`; give it a height (or let it follow the layout with
 * `responsive={false}`).
 */
export const GridCanvas = forwardRef<HTMLDivElement, GridCanvasProps>(function GridCanvas(
  { children, style, onItemClick, onDeleteKey, enabled, ...rest },
  forwardedRef,
) {
  const ref = useRef<HTMLDivElement | null>(null)
  useImperativeHandle(forwardedRef, () => ref.current as HTMLDivElement)
  const { controller, config } = useGridContext()
  const size = useElementSize(ref, config.responsive)
  useLayoutEffect(() => {
    controller.setSize(size)
  }, [controller, size])

  const handlers = useGridInteraction(ref, { onItemClick, onDeleteKey, enabled })
  const canvas = useGridStore((state) => state.layout.canvas)
  const dragging = useGridStore((state) => state.interaction !== null)

  const canvasStyle = useMemo<CSSProperties>(
    () => ({
      position: 'relative',
      boxSizing: 'border-box',
      touchAction: 'none',
      userSelect: dragging ? 'none' : undefined,
      ...(config.responsive
        ? canvas.heightMode === 'scrollable'
          ? { minHeight: canvas.height }
          : {}
        : { width: canvas.width, height: canvas.height }),
      ...style,
    }),
    [canvas.height, canvas.heightMode, canvas.width, config.responsive, dragging, style],
  )

  return (
    <div
      ref={ref}
      data-gridla-canvas=""
      data-gridla-active={dragging ? '' : undefined}
      tabIndex={rest.tabIndex ?? 0}
      {...rest}
      {...handlers}
      style={canvasStyle}
    >
      {children}
    </div>
  )
})

// ---------------------------------------------------------------------------
// GridItem
// ---------------------------------------------------------------------------

/**
 * Passed to a `GridItem` render function: the item's `GridItemView` plus props
 * for drag and resize handles.
 */
export type GridItemRenderProps = GridItemView & {
  /** Spread on the element that starts a move. */
  dragHandleProps: { [GRID_DATA.dragHandle]: string }
  /** Props for a resize handle on the given edge. */
  getResizeHandleProps: (edge: GridResizeEdge) => {
    [GRID_DATA.resizeHandle]: string
    [GRID_DATA.edge]: GridResizeEdge
  }
}

/**
 * Props for `GridItem`. `id` selects the item; the rest control drag surfaces,
 * built-in resize handles, and how the element is positioned.
 */
export type GridItemProps = Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'id'> & {
  /** Id of the item in the layout. */
  id: string
  /**
   * `true` (default): the whole element is a drag surface. `false`: only
   * elements with `dragHandleProps` start a move.
   */
  draggable?: boolean
  /** Edges to render built-in resize handles for. Default: none. */
  resizeEdges?: readonly GridResizeEdge[]
  /** Class for built-in resize handles. */
  resizeHandleClassName?: string
  /**
   * Position the element with `transform` (default) or with `left`/`top`.
   * Transform keeps layout work off the main thread during gestures.
   */
  positioning?: 'transform' | 'absolute'
  /** Render the cursor-tracked rect while dragging instead of the solved preview. Default `true`. */
  followPointer?: boolean
  children?: ReactNode | ((view: GridItemRenderProps) => ReactNode)
}

/**
 * Positions one item inside `GridCanvas`. Headless: it renders a `div` with
 * geometry styles and data attributes and leaves appearance to you.
 */
export const GridItem = forwardRef<HTMLDivElement, GridItemProps>(function GridItem(
  {
    id,
    draggable = true,
    resizeEdges,
    resizeHandleClassName,
    positioning = 'transform',
    followPointer = true,
    children,
    style,
    ...rest
  },
  ref,
) {
  const view = useGridItemView(id)
  const dragHandleProps = useMemo(
    () => ({ [GRID_DATA.dragHandle]: id }) as { [GRID_DATA.dragHandle]: string },
    [id],
  )
  const getResizeHandleProps = useCallback(
    (edge: GridResizeEdge) =>
      ({ [GRID_DATA.resizeHandle]: id, [GRID_DATA.edge]: edge }) as {
        [GRID_DATA.resizeHandle]: string
        [GRID_DATA.edge]: GridResizeEdge
      },
    [id],
  )
  const shownRect =
    view.isActive && followPointer && view.activeRect && view.interaction?.mode === 'move'
      ? view.activeRect
      : view.rect
  const itemStyle: CSSProperties = {
    boxSizing: 'border-box',
    ...rectStyle(shownRect, positioning),
    ...(view.isActive ? { zIndex: 2 } : {}),
    ...(view.isTransferring ? { opacity: 0.4 } : {}),
    ...style,
  }
  const renderProps: GridItemRenderProps = { ...view, dragHandleProps, getResizeHandleProps }

  return (
    <div
      ref={ref}
      {...rest}
      {...(draggable ? dragHandleProps : {})}
      {...{ [GRID_DATA.item]: id }}
      data-gridla-active={view.isActive ? '' : undefined}
      data-gridla-selected={view.isSelected ? '' : undefined}
      data-gridla-shifted={view.isShifted ? '' : undefined}
      data-gridla-transferring={view.isTransferring ? '' : undefined}
      style={itemStyle}
    >
      {typeof children === 'function' ? children(renderProps) : children}
      {resizeEdges?.map((edge) => (
        <div
          key={edge}
          className={resizeHandleClassName}
          {...getResizeHandleProps(edge)}
          style={resizeHandleStyle(edge)}
        />
      ))}
    </div>
  )
})

// ---------------------------------------------------------------------------
// GridPreview
// ---------------------------------------------------------------------------

/**
 * Props for `GridPreviewOutline`: `div` attributes plus the positioning mode
 * (`transform` by default).
 */
export type GridPreviewOutlineProps = HTMLAttributes<HTMLDivElement> & {
  positioning?: 'transform' | 'absolute'
}

/**
 * Renders a box where the active item will land when released. Renders
 * nothing when no gesture is in progress.
 */
export function GridPreviewOutline({
  positioning = 'transform',
  style,
  ...rest
}: GridPreviewOutlineProps) {
  const rect = useGridStore((state) => {
    if (!state.preview || !state.preview.accepted) return null
    const item = state.preview.item
    return { x: item.x, y: item.y, w: item.w, h: item.h }
  })
  if (!rect) return null
  return (
    <div
      data-gridla-preview=""
      {...rest}
      style={{
        pointerEvents: 'none',
        boxSizing: 'border-box',
        ...rectStyle(rect, positioning),
        ...style,
      }}
    />
  )
}
